/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Componentes.ClienteBillsTable;
import Componentes.ClientsTable;
import Modelo.*;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JSeparator;
import javax.swing.table.DefaultTableModel;
import src.Response;

/**
 *
 * @author araluce
 */
public class ClientDirectory extends javax.swing.JFrame {

    private Model model;
    private String dni;

    private JButton modifyButton = new JButton();
    private JButton deleteButton = new JButton();

    private JFrame thisForm = this;

    /**
     * Creates new form DirectorioCliente
     */
    public ClientDirectory(Model m, String ndni, ClientsTable table) {
        this.model = m;
        this.dni = ndni;

        initComponents();

        getContentPane().setBackground(Color.WHITE);

        final ClientManager cm = new ClientManager(model);
        final Client client = cm.findOneClientByDni(dni);

        setTitle("Directorio de " + this.dni);
        setDefaultCloseOperation(cerrarVentana());
        setSize(800, 330);
        setLayout(null);

        ClienteBillsTable clientBillTable = new ClienteBillsTable(this.model, this.dni);
        clientBillTable.setBounds(30, 50, 770, 200);

        DefaultTableModel model = (DefaultTableModel) clientBillTable.getModel();
        //"Nº ALBARÁN", "Nº RSI", "Nº LOTE", "PROCEDENCIA", "PESO TOTAL (Kg)", "F. ENTRADA", "PRECIO TOTAL"
        model.addRow(new Object[]{1234, 4321, 666, "CÁCERES", 16.50, new java.util.Date(2017, 04, 3), 125.50});

        JLabel datosCliente = new JLabel(
                "<html>"
                + "   " + client.getName() + " " + client.getLastname1() + " " + client.getLastname2()
                + "   &nbsp;&nbsp;DNI: " + client.getDni()
                + "   &nbsp;&nbsp;<span style='color: red;'>Tlf: </span>" + client.getPhone()
                + "</html>"
        );
        datosCliente.setBounds(30, 7, 770, 30);

        JSeparator separador = new JSeparator();
        separador.setBounds(30, 37, 700, 5);

        // Definiendo los botones
        modifyButton = new JButton("Modificar");
        modifyButton.setToolTipText("Modificar datos de un usuario");
        modifyButton.setBackground(new Color(40, 96, 144));
        modifyButton.setForeground(Color.WHITE);
        modifyButton.setFocusPainted(false);
        modifyButton.setBounds(170, 230, 140, 30);
        modifyButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

            }
        });

        deleteButton = new JButton("Eliminar");
        deleteButton.setToolTipText("Eliminar cliente");
        deleteButton.setBackground(new Color(201, 48, 44));
        deleteButton.setForeground(Color.WHITE);
        deleteButton.setFocusPainted(false);
        deleteButton.setBounds(370, 230, 140, 30);
        final Model optionModel = this.model;
        deleteButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (JOptionPane.showConfirmDialog(null, "¿Está seguro de que desea eliminar este cliente?", "WARNING",
                        JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                    Response response = cm.removeClient(client);
                    JOptionPane.showMessageDialog(thisForm, response.getResponse());
                }
            }
        }
        );

        add(datosCliente);

        add(separador);

        add(modifyButton);

        add(deleteButton);

        add(clientBillTable);
    }

    public int cerrarVentana() {
        int DO_NOTHING_ON_CLOSE = 0;
        int DISPOSE_ON_CLOSE = 2;
//        if (JOptionPane.showConfirmDialog(this,
//                "¿Estás seguro de cerrar esta ventana?", "Cerrar directorio",
//                JOptionPane.YES_NO_OPTION,
//                JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
//            return DISPOSE_ON_CLOSE;
//        }
//        return DO_NOTHING_ON_CLOSE;
        return DISPOSE_ON_CLOSE;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
