/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Componentes.TablaAlbaranesCliente;
import Componentes.TablaClientes;
import Modelo.*;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JSeparator;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author araluce
 */
public class DirectorioCliente extends javax.swing.JFrame {

    private Modelo modelo;
    private String dni;
    
    private JButton botonRegistrar = new JButton();
    
    private JFrame esteFormulario = this;

    /**
     * Creates new form DirectorioCliente
     */
    public DirectorioCliente(Modelo m, String ndni, TablaClientes tabla) {
        this.modelo = m;
        this.dni = ndni;
        
        initComponents();
        
        getContentPane().setBackground(Color.WHITE);
        
        ClienteManager cm = new ClienteManager();
        Cliente cliente = cm.findOneClienteByDni(modelo.getConnection(), dni);
        
        setTitle("Directorio de " + this.dni);
        setDefaultCloseOperation(cerrarVentana());
        setSize(800, 330);
        setLayout(null);
        
        TablaAlbaranesCliente tablaAlbaranesCliente = new TablaAlbaranesCliente(this.modelo, this.dni);
        tablaAlbaranesCliente.setBounds(30, 50, 770, 200);
        
        DefaultTableModel model = (DefaultTableModel) tablaAlbaranesCliente.getModel();
        //"Nº ALBARÁN", "Nº RSI", "Nº LOTE", "PROCEDENCIA", "PESO TOTAL (Kg)", "F. ENTRADA", "PRECIO TOTAL"
        model.addRow(new Object[]{1234, 4321, 666, "CÁCERES", 16.50, new java.util.Date(2017, 04, 3), 125.50});

        JLabel datosCliente = new JLabel(
                "<html>" + 
                "   " + cliente.getNombre() + " " + cliente.getApellido1() + " " + cliente.getApellido2() + 
                "   &nbsp;&nbsp;DNI: " + cliente.getDni() + 
                "   &nbsp;&nbsp;<span style='color: red;'>Tlf: </span>" + cliente.getTelefono() + 
                "</html>"
        );
        datosCliente.setBounds(30, 7, 770, 30);
        
        JSeparator separador = new JSeparator();
        separador.setBounds(30, 37, 700, 5);

        

        // Definiendo los botones

        botonRegistrar = new JButton("Modificar");
        botonRegistrar.setToolTipText("Modificar datos de un usuario");
        botonRegistrar.setBackground(new Color(40, 96, 144));
        botonRegistrar.setForeground(Color.WHITE);
        botonRegistrar.setFocusPainted(false);
        botonRegistrar.setBounds(170, 230, 140, 30);
        botonRegistrar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                
            }
        });

        add(datosCliente);
        add(separador);

        add(tablaAlbaranesCliente);
    }

    public int cerrarVentana() {
        int DO_NOTHING_ON_CLOSE = 0;
        int DISPOSE_ON_CLOSE = 2;
//        if (JOptionPane.showConfirmDialog(this,
//                "¿Estás seguro de cerrar esta ventana?", "Cerrar directorio",
//                JOptionPane.YES_NO_OPTION,
//                JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION) {
//            return DISPOSE_ON_CLOSE;
//        }
//        return DO_NOTHING_ON_CLOSE;
        return DISPOSE_ON_CLOSE;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
