/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.*;
import Componentes.*;
import java.awt.BorderLayout;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author araluce
 */
public class Principal extends javax.swing.JFrame {

    private Model model = null;
    private ClientsTable clientsTable = null;
    private JLabel inputSearchClientes = null;

    /**
     * Creates new form Principal
     */
    public Principal(Model modelo) {
        this.model = modelo;
        clientsTable = new ClientsTable(modelo);
        InputCliente inputClientes = new InputCliente(modelo, clientsTable);

        initComponents();

        this.inputSearchClientes = new JLabel();
        this.inputSearchClientes.setBorder(BorderFactory.createLineBorder(Color.black));
        this.inputSearchClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Search-24.png")));
        this.inputSearchClientes.setLayout(new BorderLayout());
        this.inputSearchClientes.add(inputClientes);

        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        this.setTitle("JAMONES EL MIRADOR - GESTIÓN DE ALBARANES");

        ClientManager cm = new ClientManager();
        ArrayList<Client> clientsArray = new ArrayList<Client>();
        clientsArray = cm.findAllClients(model.getConnection(), false);
        DefaultTableModel dtmodel = (DefaultTableModel) this.clientsTable.getModel();
        for (Client c : clientsArray) {
            dtmodel.addRow(new Object[]{c.getName(), c.getLastname1() + " " + c.getLastname2(), c.getDni(), c.getPhone()});
        }
        panelResultadoBusquedaClientes.getViewport().add(this.clientsTable);

        getContentPane().setBackground(Color.WHITE);
        panelBotones.setBackground(Color.WHITE);
        panelAreaClientes.setBackground(Color.WHITE);
        panelBusquedaClientes.setBackground(Color.WHITE);
        panelResultadoBusquedaClientes.getViewport().setBackground(Color.WHITE);

        buttonAltaClientes.setBackground(Color.WHITE);
        buttonAltaClientes.setFocusPainted(false);
        buttonGestionClientes.setBackground(Color.WHITE);
        buttonGestionClientes.setFocusPainted(false);
        panelBusquedaClientes.add(this.inputSearchClientes);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelBotones = new javax.swing.JPanel();
        buttonAltaClientes = new javax.swing.JButton();
        buttonGestionClientes = new javax.swing.JButton();
        panelAreaClientes = new javax.swing.JPanel();
        panelResultadoBusquedaClientes = new javax.swing.JScrollPane();
        panelBusquedaClientes = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelBotones.setLayout(new java.awt.GridBagLayout());

        buttonAltaClientes.setText("Alta de clientes");
        buttonAltaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonAltaClientesMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 63;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 6, 0);
        panelBotones.add(buttonAltaClientes, gridBagConstraints);

        buttonGestionClientes.setText("Gestión de clientes");
        buttonGestionClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGestionClientesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 113;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 6, 0);
        panelBotones.add(buttonGestionClientes, gridBagConstraints);

        panelBusquedaClientes.setLayout(new java.awt.GridLayout(1, 0));

        javax.swing.GroupLayout panelAreaClientesLayout = new javax.swing.GroupLayout(panelAreaClientes);
        panelAreaClientes.setLayout(panelAreaClientesLayout);
        panelAreaClientesLayout.setHorizontalGroup(
            panelAreaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelResultadoBusquedaClientes)
            .addComponent(panelBusquedaClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelAreaClientesLayout.setVerticalGroup(
            panelAreaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAreaClientesLayout.createSequentialGroup()
                .addComponent(panelBusquedaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelResultadoBusquedaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(188, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelBotones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelAreaClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(9, 9, 9)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBotones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelAreaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAltaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAltaClientesMouseClicked
        ClientRegister ac = new ClientRegister(model, clientsTable);
        ac.setLocationRelativeTo(this);
        ac.setVisible(true);
    }//GEN-LAST:event_buttonAltaClientesMouseClicked

    private void buttonGestionClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGestionClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonGestionClientesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAltaClientes;
    private javax.swing.JButton buttonGestionClientes;
    private javax.swing.JPanel panelAreaClientes;
    private javax.swing.JPanel panelBotones;
    private javax.swing.JPanel panelBusquedaClientes;
    private javax.swing.JScrollPane panelResultadoBusquedaClientes;
    // End of variables declaration//GEN-END:variables
}
