/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.*;
import Componentes.*;
import java.awt.BorderLayout;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author araluce
 */
public class Principal extends javax.swing.JFrame {

    private Model model = null;
    private ClientsTable clientsTable = null;
    private JLabel inputSearchClientes = null;

    /**
     * Creates new form Principal
     */
    public Principal(Model modelo) {
        setUndecorated(true);
        setVisible(true);
        this.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        
        this.model = modelo;
        clientsTable = new ClientsTable(modelo);
        InputCliente inputClientes = new InputCliente(modelo, clientsTable);

        initComponents();
        Color colorHeader = new Color(40, 96, 144);
        this.header.setBackground(colorHeader);
        this.exitButton.setBackground(Color.WHITE);
        this.exitButton.setFocusPainted(false);
        this.minimizeButton.setBackground(Color.WHITE);
        this.minimizeButton.setFocusPainted(false);

        this.inputSearchClientes = new JLabel();
        this.inputSearchClientes.setBorder(BorderFactory.createLineBorder(Color.black));
        this.inputSearchClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Search-24.png")));
        this.inputSearchClientes.setLayout(new BorderLayout());
        this.inputSearchClientes.add(inputClientes);

        this.setTitle("EM - Gestión");
        this.title.setText("JAMONES EL MIRADOR - GESTIÓN DE ALBARANES");

        ClientManager cm = new ClientManager();
        ArrayList<Client> clientsArray = new ArrayList<Client>();
        clientsArray = cm.findAllClients(model.getConnection(), false);
        DefaultTableModel dtmodel = (DefaultTableModel) this.clientsTable.getModel();
        for (Client c : clientsArray) {
            dtmodel.addRow(new Object[]{c.getName(), c.getLastname1() + " " + c.getLastname2(), c.getDni(), c.getPhone()});
        }
        panelResultadoBusquedaClientes.getViewport().add(this.clientsTable);

        getContentPane().setBackground(Color.WHITE);
        panelAreaClientes.setBackground(Color.WHITE);
        panelBusquedaClientes.setBackground(Color.WHITE);
        panelResultadoBusquedaClientes.getViewport().setBackground(Color.WHITE);

        buttonAltaClientes.setBackground(Color.WHITE);
        buttonAltaClientes.setFocusPainted(false);
        panelBusquedaClientes.add(this.inputSearchClientes);

    }

    /**
     * s
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        header = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        minimizeButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        buttonAltaClientes = new javax.swing.JButton();
        buttonGestionClientes = new javax.swing.JButton();
        panelAreaClientes = new javax.swing.JPanel();
        panelBusquedaClientes = new javax.swing.JPanel();
        panelResultadoBusquedaClientes = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        header.setAlignmentX(0.0F);
        header.setAlignmentY(0.0F);
        header.setMaximumSize(getMaximumSize());

        title.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));

        minimizeButton.setFont(new java.awt.Font("DejaVu Sans", 1, 14)); // NOI18N
        minimizeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Minimize-16.png"))); // NOI18N
        minimizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimizeButtonActionPerformed(evt);
            }
        });

        exitButton.setFont(new java.awt.Font("DejaVu Sans", 1, 12)); // NOI18N
        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/Exit-16.png"))); // NOI18N
        exitButton.setPreferredSize(new java.awt.Dimension(24, 24));
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridBagLayout());

        buttonAltaClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/AddUser-64.png"))); // NOI18N
        buttonAltaClientes.setText("Alta de clientes");
        buttonAltaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonAltaClientesMouseClicked(evt);
            }
        });
        buttonAltaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAltaClientesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 63;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 6, 0);
        jPanel1.add(buttonAltaClientes, gridBagConstraints);

        buttonGestionClientes.setText("Gestión de clientes");
        buttonGestionClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGestionClientesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 113;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 6, 0);
        jPanel1.add(buttonGestionClientes, gridBagConstraints);

        javax.swing.GroupLayout headerLayout = new javax.swing.GroupLayout(header);
        header.setLayout(headerLayout);
        headerLayout.setHorizontalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerLayout.createSequentialGroup()
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(minimizeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE))
                .addContainerGap())
        );
        headerLayout.setVerticalGroup(
            headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerLayout.createSequentialGroup()
                .addGroup(headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(headerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(minimizeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelBusquedaClientes.setLayout(new java.awt.GridLayout(1, 0));

        javax.swing.GroupLayout panelAreaClientesLayout = new javax.swing.GroupLayout(panelAreaClientes);
        panelAreaClientes.setLayout(panelAreaClientesLayout);
        panelAreaClientesLayout.setHorizontalGroup(
            panelAreaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelResultadoBusquedaClientes)
            .addComponent(panelBusquedaClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelAreaClientesLayout.setVerticalGroup(
            panelAreaClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAreaClientesLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(panelBusquedaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelResultadoBusquedaClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(228, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelAreaClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(header, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(header, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelAreaClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAltaClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAltaClientesMouseClicked
        ClientRegister ac = new ClientRegister(model, clientsTable);
        ac.setLocationRelativeTo(this);
        ac.setVisible(true);
    }//GEN-LAST:event_buttonAltaClientesMouseClicked

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void minimizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimizeButtonActionPerformed
         setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeButtonActionPerformed

    private void buttonGestionClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGestionClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonGestionClientesActionPerformed

    private void buttonAltaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAltaClientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonAltaClientesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAltaClientes;
    private javax.swing.JButton buttonGestionClientes;
    private javax.swing.JButton exitButton;
    private javax.swing.JPanel header;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton minimizeButton;
    private javax.swing.JPanel panelAreaClientes;
    private javax.swing.JPanel panelBusquedaClientes;
    private javax.swing.JScrollPane panelResultadoBusquedaClientes;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
